In [1]:
import zipfile
import json
import pandas as pd
import os
import gc

In [4]:
nombre_archivo_zip = 'Google Maps-20231115T202205Z-001.zip'

# Inicializar una lista para almacenar DataFrames individuales
reviews = []
metadata = []

# Abrir el archivo ZIP
with zipfile.ZipFile(nombre_archivo_zip, 'r') as zip_ref:

    # Obtener una lista de los archivos de reviews
    archivos_reviews = [f for f in zip_ref.namelist() if f.startswith("Google Maps/reviews-estados") and f.endswith('.json')]
    # Iterar sobre los archivos en la carpeta
    for nombre_archivo in archivos_reviews:
        with zip_ref.open(nombre_archivo) as json_file:
            # Leer el contenido del archivo como una cadena
            json_str = json_file.read().decode('utf-8')

            # Dividir la cadena en objetos JSON individuales
            objetos_json = [json.loads(obj_str) for obj_str in json_str.split('\n') if obj_str.strip()]

            # Cargar los archivos en un dataframe
            df = pd.DataFrame(objetos_json)
            reviews.append(df)

    # Obtener una lista de los archivos de reviews
    metadata_sitios = [f for f in zip_ref.namelist() if f.startswith("Google Maps/metadata-sitios") and f.endswith('.json')]
    # Iterar sobre los archivos en la carpeta
    for sitio in metadata_sitios:
        with zip_ref.open(sitio) as meta_json:
            # Leer el contenido del archivo como una cadena
            meta_str = meta_json.read().decode('utf-8')

            # Dividir la cadena en objetos JSON individuales
            objetos_meta = [json.loads(obj_str1) for obj_str1 in meta_str.split('\n') if obj_str1.strip()]

            # Cargar los archivos en un dataframe
            meta = pd.DataFrame(objetos_meta)
            metadata.append(meta)

# Concatenar todos los DataFrames en uno solo
if reviews:
    df_reviews = pd.concat(reviews, ignore_index=True)

# Concatenar todos los DataFrames en uno solo
if metadata:
    df_metadata = pd.concat(metadata, ignore_index=True)

In [5]:
df_reviews.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,103388204835998302713,Mmustangg Ggnatsumm,1592280059342,5,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2
1,101493059298687786658,Luis Antonio,1535471202673,5,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2
2,108065566978040119641,Abby N,1548907384201,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2
3,112164287381301303443,Marsha Davidson,1531441401770,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2
4,112590721316665651581,Respect my Hussle!,1500047718230,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2

In [6]:
df_metadata.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,None,32.388300,-83.357100,[Pharmacy],4.9,16,None,"[[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...","{'Service options': ['In-store shopping', 'Sam...",Open ⋅ Closes 6PM,"[0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.215290,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,None,34.058092,-118.292130,[Korean restaurant],4.4,18,None,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,None,34.023669,-118.232930,[Fabric store],3.3,6,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,None,34.036694,-118.249421,[Fabric store],4.3,7,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...

In [7]:
gc.collect()

7

In [8]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8538485 entries, 0 to 8538484
Data columns (total 8 columns):
 #   Column   Dtype
---  ------   -----
 0   user_id  object
 1   name     object
 2   time     int64
 3   rating   int64
 4   text     object
 5   pics     object
 6   resp     object
 7   gmap_id  object
dtypes: int64(2), object(6)
memory usage: 521.1+ MB

In [10]:
df_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275001 entries, 0 to 275000
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   name              274994 non-null  object
 1   address           264939 non-null  object
 2   gmap_id           275001 non-null  object
 3   description       13155 non-null   object
 4   latitude          275001 non-null  float64
 5   longitude         275001 non-null  float64
 6   category          272740 non-null  object
 7   avg_rating        275001 non-null  float64
 8   num_of_reviews    275001 non-null  int64
 9   price             13450 non-null   object
 10  hours             192448 non-null  object
 11  MISC              194972 non-null  object
 12  state             195523 non-null  object
 13  relative_results  238771 non-null  object
 14  url               275001 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 31.5+ MB

In [11]:
reviews_completo = pd.merge(df_reviews, df_metadata, on="gmap_id", how="inner")
reviews_completo.head()

,user_id,name_x,time,rating,text,pics,resp,gmap_id,name_y,address,...,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,103563353519118158246,Peri Gray,1516122675780,5,Great place to care for our children.,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
1,103563353519118158246,Peri Gray,1516122675780,5,Great place to care for our children.,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
2,101824980797027243148,Suzy Berndt,1532922350314,5,Th sw y are so nice,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
3,101824980797027243148,Suzy Berndt,1532922350314,5,Th sw y are so nice,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
4,108711640480272772398,Rosemary Red Legs,1530969093932,5,Went with my daughter,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...

In [12]:
reviews_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29601 entries, 0 to 29600
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           29601 non-null  object
 1   name_x            29601 non-null  object
 2   time              29601 non-null  int64
 3   rating            29601 non-null  int64
 4   text              17467 non-null  object
 5   pics              665 non-null    object
 6   resp              3428 non-null   object
 7   gmap_id           29601 non-null  object
 8   name_y            29601 non-null  object
 9   address           29482 non-null  object
 10  description       2442 non-null   object
 11  latitude          29601 non-null  float64
 12  longitude         29601 non-null  float64
 13  category          29549 non-null  object
 14  avg_rating        29601 non-null  float64
 15  num_of_reviews    29601 non-null  int64
 16  price             3084 non-null   object
 17  hours             25256 non-null  object
 18  MISC              26086 non-null  object
 19  state             25586 non-null  object
 20  relative_results  28103 non-null  object
 21  url               29601 non-null  object
dtypes: float64(3), int64(3), object(16)
memory usage: 5.0+ MB

In [13]:
reviews_completo1 = pd.merge(df_reviews, df_metadata, on="gmap_id", how="left")
reviews_completo1.head()

,user_id,name_x,time,rating,text,pics,resp,gmap_id,name_y,address,...,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,103388204835998302713,Mmustangg Ggnatsumm,1592280059342,5,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,101493059298687786658,Luis Antonio,1535471202673,5,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,108065566978040119641,Abby N,1548907384201,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,112164287381301303443,Marsha Davidson,1531441401770,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,112590721316665651581,Respect my Hussle!,1500047718230,4,None,None,None,0x8760bbfbfa6847e1:0xad949b36fcb194a2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
reviews_completo1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8544251 entries, 0 to 8544250
Data columns (total 22 columns):
 #   Column            Dtype
---  ------            -----
 0   user_id           object
 1   name_x            object
 2   time              int64
 3   rating            int64
 4   text              object
 5   pics              object
 6   resp              object
 7   gmap_id           object
 8   name_y            object
 9   address           object
 10  description       object
 11  latitude          float64
 12  longitude         float64
 13  category          object
 14  avg_rating        float64
 15  num_of_reviews    float64
 16  price             object
 17  hours             object
 18  MISC              object
 19  state             object
 20  relative_results  object
 21  url               object
dtypes: float64(4), int64(2), object(16)
memory usage: 1.4+ GB

In [15]:
gc.collect()

493

In [16]:
reviews_completo["category"].value_counts()

category
[Nail salon]                                                  645
[Bar]                                                         565
[Barber shop]                                                 545
[Park]                                                        529
[Restaurant]                                                  521
                                                             ...
[Phone repair service, Computer repair service]                10
[Eye care center, Contact lenses supplier, Optometrist]        10
[Paint store, Hardware store]                                  10
[Surgical center]                                              10
[Federal credit union, ATM, Credit union, Mortgage lender]     10
Name: count, Length: 783, dtype: int64

In [26]:
categorias = reviews_completo["category"].explode().unique()
categorias

array([None, 'Youth social services organization', 'Auto repair shop',
       'Truck repair shop', 'Auto body shop', 'Towing service',
       'Coffee shop', 'Cafe', 'Coffee store', 'Espresso bar',
       'Nail salon', 'Gift shop', 'Bar', 'Animal feed store',
       'Beauty salon', 'Boat dealer', 'Boat repair shop', 'Park',
       'Urgent care center', 'Medical clinic', 'Lake', 'Uniform store',
       'HVAC contractor', 'Air conditioning contractor',
       'Heating contractor', 'Mechanical contractor', 'Metal fabricator',
       'Hair salon', 'Motorcycle dealer', 'Hot tub store',
       'Billiards supply store', 'Furniture store',
       'Hot tub repair service', 'Outdoor furniture store',
       'Swimming pool contractor', 'Swimming pool repair service',
       'Swimming pool supply store', 'Baseball field',
       'Beauty supply store', 'Grocery store', 'Transportation service',
       'Vitamin & supplements store', 'Sports nutrition store',
       'Weight loss service', 'Church', 'Tourist attraction',
       'Car dealer', 'Auto glass shop', 'Auto parts store',
       'Chevrolet dealer', 'Dentist', 'Cosmetic dentist',
       'Conference center', 'Banquet hall', 'Clothing store',
       'Trailer supply store', 'Truck accessories store',
       'Family practice physician', 'Fast food restaurant',
       'American restaurant', 'Chicken restaurant',
       'Chicken wings restaurant', 'Gas station', 'Convenience store',
       'Restaurant', 'Beer store', 'Liquor store', 'Wine store',
       'Car repair and maintenance',
       'Church of Jesus Christ of Latter-day Saints', 'Christian church',
       'Church of Christ', 'Genealogist', 'Mission',
       'Non-profit organization', 'Place of worship',
       'Religious organization', 'Seminary', 'Lounge', 'Mattress store',
       'Barber shop', 'Waxing hair removal service', 'Tire shop',
       'Garbage dump', 'Veterinarian', 'Hospital',
       'Self-storage facility', 'Cell phone store',
       'Internet service provider', 'Telecommunications service provider',
       'Wholesale food store', 'Construction equipment supplier',
       'Farm equipment supplier', 'Wedding venue', 'Fireworks store',
       'Eye care center', 'Contact lenses supplier', 'Optometrist',
       'Lutheran church', 'Tobacco shop', 'Dental implants periodontist',
       'DJ service', 'Event planner', 'Party equipment rental service',
       'Photographer', 'Video production service', 'Wedding photographer',
       'Wedding planner', 'Book store', 'Sportswear store',
       'Real estate developer', 'Car accessories store',
       'Car battery store', 'Tool rental service', 'University',
       'College', 'Casino', 'Vacuum cleaner repair shop', 'Store',
       'Paint store', 'Home improvement store', 'Bagel shop', 'Bakery',
       'Breakfast restaurant', 'Insurance agency',
       'Auto insurance agency', 'Home insurance agency',
       'Life insurance agency', "Renter's insurance agency",
       'Screen printing supply store', 'Federal credit union', 'ATM',
       'Credit union', 'Mortgage lender', 'Auto wrecker', 'Donut shop',
       'Steak house', 'Wheel alignment service', 'Brake shop', 'Day spa',
       'Coffee roasters', 'Pastry shop', 'Tea house', 'Wi-Fi spot',
       'Pet groomer', 'Gym', 'Cell phone accessory store',
       'Apartment complex', 'Apartment building', 'Tractor dealer',
       'Equipment rental agency', 'Industrial equipment supplier',
       'Lawn mower store', 'Oil change service', 'Battery store',
       'Car inspection station', 'Drug store', 'Cosmetics store',
       'Greeting card shop', 'Perfume store', 'Stationery store',
       'Flooring store', 'Sporting goods store', 'Wholesaler',
       'Granite supplier', 'Stone supplier', 'Tile store', 'Truck stop',
       'Laundry', 'Pizza Takeout', 'Winery', 'Used tire shop',
       'Water sports equipment rental service',
       'Canoe & kayak rental service', 'Service establishment',
       'Fitness center', 'Tanning salon', 'Weightlifting area',
       'Dental clinic', 'Teeth whitening service',
       'Engine rebuilding service', 'Auto air conditioning service',
       'Mechanic', 'Transmission shop', 'Bar & grill', 'Ford dealer',
       'Auto tune up service', 'Used car dealer', 'Car wash',
       'Outdoor equestrian facility', 'Equestrian facility',
       'Horse boarding stable', 'Horseback riding service',
       'Security system supplier', 'Fire protection equipment supplier',
       'Glass & mirror shop', 'Locksmith', 'Safe & vault shop',
       'Muffler shop', 'Heating oil supplier',
       'Air conditioning repair service', 'Oil & natural gas company',
       'Propane supplier', 'Wildlife refuge', 'Plumber',
       'Little league field', 'Art center', 'Art handcraft', 'Art studio',
       'Event venue', 'Bedding store', 'Futon store', 'Community center',
       'Skateboard park', 'Fishing pier', 'Mountain peak',
       'Nature preserve', 'Tattoo shop', 'Dollar store', 'Discount store',
       'Ski club', 'Hiking area', 'Wood stove shop',
       'Vacuum cleaner store', 'Pizza restaurant', 'Pumpkin patch',
       'Beach volleyball court', 'Karaoke bar', 'Computer store',
       'Computer repair service', 'Military school', 'Private university',
       'Hardware store', 'Lumber store', 'Furnace repair service',
       'Pharmacy', 'General store', 'Massage spa', 'Art gallery',
       'Chiropractor', 'Craft store', 'Fraternal organization',
       'Performing arts theater', 'Picture frame shop', 'Caterer',
       'Chocolate shop', 'Dessert shop', 'Florist', 'Gift basket store',
       'Juice shop', 'Well drilling contractor', 'Excavating contractor',
       'General contractor', 'Sports complex', 'Recreation center',
       'Motorcycle shop', 'Motorcycle parts store',
       'Motorcycle repair shop', 'Used motorcycle dealer', 'Acura dealer',
       'Car finance and loan company', 'Truck dealer',
       'Used truck dealer', 'Auto dent removal service', 'Auto painting',
       'Bingo hall', 'Catering food and drink supplier', 'Sandwich shop',
       'Veterinary pharmacy', 'Boutique', 'Boot store', 'Jewelry store',
       'Western apparel store', 'Pet supply store', 'Party store',
       'Movie theater', 'Moving and storage service',
       'Moving supply store', 'Packaging supply store',
       'Trailer rental service', 'Truck rental agency',
       'Van rental agency', 'Diner', 'Garden center', 'Company',
       'Audio visual equipment supplier', 'Vaporizer store', 'ATV dealer',
       'Pub', 'Baby clothing store', 'Norwegian restaurant',
       'Appliance repair service', 'Appliance store',
       'Refrigerator store', 'Pizza delivery', 'Photo shop',
       'Digital printer', 'Photo lab', 'Car racing track',
       'Antique store', 'Social services organization', 'Grain elevator',
       'Chrysler dealer', 'Dodge dealer', 'Jeep dealer', 'Golf course',
       'Truck parts supplier', 'Custom t-shirt store', 'Embroidery shop',
       'Engraver', 'T-shirt store', 'Baseball', 'Discount supermarket',
       'School supply store', 'Toy store', 'Department of Transportation',
       'Veterans organization', 'Down home cooking restaurant',
       'Takeout Restaurant', 'Pasta shop', 'Salad shop',
       'Soup restaurant', 'Car detailing service',
       'Diesel engine repair service', 'Trailer repair shop', 'Food bank',
       'Paint manufacturer', 'Painting', 'Paintings store',
       'Wallpaper store', 'Automobile storage facility',
       'Boat storage facility', 'RV storage facility', 'Storage facility',
       'Cocktail bar', 'Car rental agency', 'Fishing store',
       'Shipping and mailing service', 'Business center',
       'Freight forwarding service', 'Mailbox rental service',
       'Notary public', 'Office supply store', 'Print shop',
       'Shredding service', 'General practitioner', 'Kennel',
       'Home goods store', 'Motorsports store', 'ATV repair shop',
       'Chauffeur service', 'Snowmobile dealer', 'RV park',
       'Trucking company', 'Sand plant', 'Bank', 'Health food restaurant',
       'Boat ramp', 'Tool store', 'Camp', 'Campground',
       'Acupuncture clinic', 'Commercial refrigeration',
       'Event ticket seller', 'Bed shop', 'Bedroom furniture store',
       'United Methodist church', 'Buick dealer', 'Car leasing service',
       'GMC dealer', 'Shoe store', "Women's clothing store",
       'Alternative medicine practitioner', 'Doctor',
       'Pain management physician', 'Physical therapist',
       'Physical therapy clinic', 'Rehabilitation center',
       'Sports medicine clinic', 'Walk-in clinic',
       'Apartment rental agency', 'Property management company',
       'Electrical supply store', 'Plumbing supply store',
       'Dominican restaurant', 'Insurance company',
       'Motorcycle insurance agency', 'Technical school',
       'Public educational institution', 'Tax preparation service',
       'Tax consultant', 'Eyebrow bar', 'Eyelash salon',
       'Alternator supplier', 'Auto radiator repair service',
       'Employment agency', 'Recruiter', 'Temp agency',
       'Real estate agents', 'Commercial real estate agency',
       'Screen printer', 'Addiction treatment center',
       'Alcoholism treatment program', 'Senior citizen center',
       'Obstetrician-gynecologist', 'Italian restaurant', 'Laundromat',
       'Real estate agency', 'Real estate consultant',
       'Electronics store', 'Furniture rental service',
       'Personal injury attorney', 'Criminal justice attorney',
       'Estate planning attorney', 'Attorney', 'Social security attorney',
       'Landscaper', 'Landscape designer', 'Landscaping supply store',
       'Lawn care service', 'Masonry contractor', 'Hair removal service',
       'Hairdresser', 'Ice cream shop', 'Farm', 'Dairy farm',
       'Pet sitter', 'Physical fitness program', 'Body piercing shop',
       'Tattoo and piercing shop', 'Taco restaurant',
       'Blood donation center', 'Hookah store',
       'Building materials store', 'Financial consultant',
       'Financial planner', 'State government office', 'Dry cleaner',
       'Lawn mower repair service', 'Cape Verdean restaurant',
       'Seafood restaurant', 'Welding supply store', 'Night club',
       'Pet trainer', 'Restaurant supply store', 'Candy store',
       'Security guard service', 'Security service', 'Catholic church',
       'Ear piercing service', 'Personal trainer', 'Spa', 'Cigar shop',
       'Pet boarding service', 'Pet adoption service', 'Wellness center',
       'Office equipment supplier', 'Office furniture store',
       'Paper distributor', 'Chinese restaurant', 'Portrait studio',
       'Delivery Chinese restaurant', 'Artist', 'Hookah bar',
       'Animal shelter', 'Jeweler', 'Car stereo store', 'Art school',
       'Festival', 'Consignment shop', 'Facial spa', 'Skin care clinic',
       'Auto electrical service', 'Phone repair service', 'Supermarket',
       'Electrician', 'Small engine repair service',
       "Children's clothing store", 'Baby store', 'Maternity store',
       'Dental hygienist', 'Dental implants provider',
       'Emergency dental service', 'Agricultural service',
       'Building materials supplier', 'Insurance broker',
       'Ophthalmologist', 'Martial arts school', 'Self defense school',
       'Pottery classes', 'Title company', 'Mexican restaurant',
       'Railroad company', 'Needlework shop', 'Mobile home park',
       'Nutritionist', 'Delivery Restaurant', 'Window tinting service',
       'Auto restoration service', 'Auto sunroof shop',
       'Glass repair service', 'Window installation service',
       'Window supplier', 'Aromatherapy supply store', 'Candle store',
       'Novelty store', 'Fashion accessories store',
       "Men's clothing store", 'Gun shop', 'Stadium',
       'Pest control service', 'Shower door shop',
       'Community health centre', 'Medical Center', 'Courier service',
       'Delivery service', 'Dog day care center', 'Barn',
       'Animal hospital', 'Saddlery', 'Tack shop', 'Wholesale jeweler',
       'Jewelry buyer', 'Marine supply store', 'Pet store',
       'Outdoor sports store', 'Podiatrist', 'Foot care', 'Surgeon',
       'Musical instrument store', 'Record store', 'Game store',
       'Truck topper supplier', 'Optician', 'Non-denominational church',
       'Garage door supplier', 'Dog trainer', 'Plant nursery',
       'Wholesale plant nursery', 'Contractor', 'Recycling center',
       'Bowling alley', 'Massage therapist', 'Marina',
       'Plus size clothing store', 'Cannabis store',
       'Horse trailer dealer', 'Utility trailer dealer',
       'Homeless service', 'Homeless shelter', 'Modular home dealer',
       'Mobile home dealer', 'Food court', 'Amusement park ride',
       'Bicycle rental service', 'Bicycle repair shop', 'Bicycle Shop',
       'Ski rental service', 'Electronic parts supplier',
       'Telephone company', 'Sushi takeaway', 'Dog park',
       'Racquetball club', 'Post office', 'Logistics service',
       'Money order service', 'Passport office', 'Wholesale grocer',
       'Pet care service', 'Baptist church', 'Roofing contractor',
       'Storage', 'Warehouse', 'Historical landmark',
       'Hydroponics equipment supplier', 'Jeans shop', 'Swimwear store',
       'Underwear store', 'Rock shop', 'Wellness program',
       'Data recovery service', 'Outdoor clothing and equipment shop',
       'Education center', 'Training centre', 'Tile contractor',
       'Assemblies of God church', 'Picnic ground', 'Real estate',
       'Corporate office', 'Repair service', 'Leather goods store',
       'Newspaper publisher', 'Classified ads newspaper publisher',
       'Commercial printer', 'Newspaper advertising department',
       'Natural goods store', 'Construction machine rental service',
       'Fence supply store', 'Sign shop', 'Athletic club',
       'Computer consultant', 'Computer software store',
       'Computer support and services', 'Public library',
       'Metaphysical supply store', 'Homeopath', 'Incense supplier',
       'Psychic', 'Public sauna', 'Lawn equipment rental service',
       'Outlet store', 'Carpet installer', 'Carpet store',
       'Interior designer', 'Wood floor installation service',
       'Fairground', 'Running store', 'Laundry service',
       'Self service car wash', 'Museum', 'Entertainment and recreation',
       'Blood bank', 'Japanese steakhouse', 'Mailing service',
       'Thrift store', 'Orthopedic surgeon', 'Orthopedic clinic',
       'Agricultural production', 'Greenhouse', 'Internet cafe',
       'Auditorium', 'Garden', 'Disc golf course', 'Hearing aid store',
       'Public university', 'Library', 'Oil field equipment supplier',
       'Protestant church', 'Asian restaurant', 'Hot pot restaurant',
       'Gutter cleaning service', 'Siding contractor',
       'General practice attorney', 'Law firm', 'Legal services',
       'Real estate attorney', 'Trial attorney', 'Shoe repair shop',
       'Burrito restaurant', 'Gay bar', 'Gay night club',
       'Latin American restaurant', 'Spanish restaurant', 'Urologist',
       'Emergency room', 'Auction house', 'Concrete contractor',
       'Mortgage broker', 'Pawn shop', 'Distribution service',
       'Beauty product supplier', 'Health and beauty shop', 'Watch store',
       'Tapas restaurant', 'Deli', 'Indian grocery store',
       'Indian takeaway', 'Boxing gym', 'Diamond dealer',
       'Jewelry designer', 'Jewelry repair service', 'Garage builder',
       'Custom home builder', 'Gazebo builder', 'Home builder',
       'Shed builder', 'Vegetarian restaurant', 'Kitchen supply store',
       'Chinaware store', 'Cutlery store', 'Gourmet grocery store',
       'Fuel supplier', 'Used furniture store', 'Photography service',
       'Photography studio', 'United Church of Christ', 'Internist',
       'Wheel store', 'Pottery store', 'Diesel fuel supplier', 'Tailor',
       'Gastropub', 'Auto machine shop', 'Construction',
       'Helium gas supplier', 'Industrial gas supplier',
       'Welding gas supplier', 'Computer security service',
       'Used computer store', 'Dermatologist', 'Camping store',
       'Medical laboratory', 'Diagnostic center', 'Drug testing service',
       'Pediatric dentist', 'Japanese restaurant',
       'Department of Social Services', 'Pentecostal church',
       'Apostolic church', 'Medical office', "Women's health clinic",
       'Motorcycles', 'Music store', 'Tex-Mex restaurant',
       'Guatemalan restaurant', 'Topsoil supplier', 'Mulch supplier',
       'After school program', 'Kickboxing school', 'Taxi service',
       'Variety store', 'Emergency training', 'Emergency training school',
       'Training school', 'Auto body parts supplier', 'Aikido school',
       'Jujitsu school', 'Karate school', 'Kung fu school',
       'Muay Thai boxing gym', 'Taekwondo school', 'Wrestling school',
       'City government office', 'Cajun restaurant',
       'Caribbean restaurant', 'Southern restaurant (US)', 'Beach',
       'Hair extension technician', 'Home inspector',
       'Building inspector', 'Commercial real estate inspector',
       'Wine bar', 'Wildlife rescue service', 'Used auto parts store',
       'Tuxedo shop', 'Lunch restaurant', 'Endodontist', 'Orthodontist',
       'Periodontist', 'Colombian restaurant', 'Parking garage',
       'Playground', 'Animal control service', 'Goldsmith', 'Silversmith',
       'Watch repair service', 'Oral surgeon',
       'Energy equipment and solutions', 'Hobby store', 'Kite shop',
       'Model train store', 'Scrap metal dealer', 'Religious goods store',
       'Tree service', 'Community garden', 'Cultural center',
       'Wax supplier', 'Land Rover dealer', 'Internet shop',
       'Asian fusion restaurant', "Farmers' market", 'Flower delivery',
       'Flower designer', 'Herb shop', 'Health food store',
       'Racing car parts store', 'Subaru dealer',
       "Children's furniture store", 'Masonry supply store',
       'Skateboard shop', 'Snowboard shop', 'Sunglasses store',
       'Surgical center', 'RV repair shop', 'River', 'Culture',
       'Educational testing service', 'Accountant', 'Chinese takeaway',
       'Alternative fuel station', 'Electric vehicle charging station',
       'Portuguese restaurant', 'Used book store', 'Car alarm supplier',
       'Clothing alteration service', 'Leather cleaning service',
       'Auto upholsterer', 'Upholstery cleaning service', 'Country club',
       'Private golf course', 'Tennis club', 'Park & ride',
       'Haunted house', 'Condominium complex', 'Hawaiian restaurant',
       'Christmas tree farm', 'Grocery delivery service',
       'Ecuadorian restaurant', 'Garbage dump service',
       'Frozen yogurt shop', 'Escape room center', 'Live music venue',
       'Outdoor movie theater', 'Midwife', 'Denture care center',
       'Emergency veterinarian service', 'Cardiologist', 'Medical group',
       'Bouncy castle hire', "Children's party service",
       'Event management company', 'Party planner', 'Wine cellar',
       'Barber supply store', 'Club', 'Hunting club', 'Veterans hospital',
       'Dance school', 'Emergency care service',
       'Occupational medical physician', 'Donations center',
       'Gluten-free restaurant', 'Refrigerator repair service',
       'Small appliance repair service', 'Washer & dryer repair service',
       'Business to business service', 'Auto spring shop', 'Swim club',
       'Radio broadcaster', 'Bubble tea store', 'Butcher shop',
       'Mobile phone repair shop', 'Electrical repair shop', 'Golf club',
       'Indoor cycling', 'Yoga studio'], dtype=object)

In [27]:
len(categorias)

846

In [28]:
# Se abre el dataframe en las diferentes categorías
reviews_completo = reviews_completo.explode("category")
reviews_completo.head()

,user_id,name_x,time,rating,text,pics,resp,gmap_id,name_y,address,...,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,103563353519118158246,Peri Gray,1516122675780,5,Great place to care for our children.,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
1,103563353519118158246,Peri Gray,1516122675780,5,Great place to care for our children.,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
2,101824980797027243148,Suzy Berndt,1532922350314,5,Th sw y are so nice,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
3,101824980797027243148,Suzy Berndt,1532922350314,5,Th sw y are so nice,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...
4,108711640480272772398,Rosemary Red Legs,1530969093932,5,Went with my daughter,None,None,0x532af45db8f30779:0xd9be9359f1e56178,CRST WIC Office,"CRST WIC Office, 16618 243rd Avenue, Eagle But...",...,-101.239919,None,4.7,8,None,None,None,None,"[0x532af4588c5f80b1:0x30071640ecb03b5, 0x532af...",https://www.google.com/maps/place//data=!4m2!3...

In [29]:
reviews_completo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71159 entries, 0 to 29600
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           71159 non-null  object
 1   name_x            71159 non-null  object
 2   time              71159 non-null  int64
 3   rating            71159 non-null  int64
 4   text              42715 non-null  object
 5   pics              1358 non-null   object
 6   resp              10635 non-null  object
 7   gmap_id           71159 non-null  object
 8   name_y            71159 non-null  object
 9   address           70834 non-null  object
 10  description       9481 non-null   object
 11  latitude          71159 non-null  float64
 12  longitude         71159 non-null  float64
 13  category          71107 non-null  object
 14  avg_rating        71159 non-null  float64
 15  num_of_reviews    71159 non-null  int64
 16  price             10895 non-null  object
 17  hours             65222 non-null  object
 18  MISC              63514 non-null  object
 19  state             65637 non-null  object
 20  relative_results  68703 non-null  object
 21  url               71159 non-null  object
dtypes: float64(3), int64(3), object(16)
memory usage: 12.5+ MB

In [31]:
palabra_clave = "restaurant"
reviews_restaurant = reviews_completo.dropna(subset="category")
filtro = reviews_restaurant["category"].str.contains(palabra_clave, case=False)
restaurantes = reviews_restaurant[filtro]
restaurantes.head()

,user_id,name_x,time,rating,text,pics,resp,gmap_id,name_y,address,...,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
1274,111058951077443588250,Mellissa Newling,1491249563055,3,Orders wrong every time I go here. Takes forev...,None,None,0x878011faadb8eead:0xe778cbfd3bfbed0,KFC,"KFC, 603 E Sioux Ave, Pierre, SD 57501",...,-100.347168,Fast food restaurant,2.4,18,$,"[[Monday, 11AM–9PM], [Tuesday, 11AM–9PM], [Wed...","{'Service options': ['Delivery', 'Takeout'], '...",Permanently closed,"[0x878011faac2b47fb:0x544e98484ed978fc, 0x8780...",https://www.google.com/maps/place//data=!4m2!3...
1274,111058951077443588250,Mellissa Newling,1491249563055,3,Orders wrong every time I go here. Takes forev...,None,None,0x878011faadb8eead:0xe778cbfd3bfbed0,KFC,"KFC, 603 E Sioux Ave, Pierre, SD 57501",...,-100.347168,American restaurant,2.4,18,$,"[[Monday, 11AM–9PM], [Tuesday, 11AM–9PM], [Wed...","{'Service options': ['Delivery', 'Takeout'], '...",Permanently closed,"[0x878011faac2b47fb:0x544e98484ed978fc, 0x8780...",https://www.google.com/maps/place//data=!4m2!3...
1274,111058951077443588250,Mellissa Newling,1491249563055,3,Orders wrong every time I go here. Takes forev...,None,None,0x878011faadb8eead:0xe778cbfd3bfbed0,KFC,"KFC, 603 E Sioux Ave, Pierre, SD 57501",...,-100.347168,Chicken restaurant,2.4,18,$,"[[Monday, 11AM–9PM], [Tuesday, 11AM–9PM], [Wed...","{'Service options': ['Delivery', 'Takeout'], '...",Permanently closed,"[0x878011faac2b47fb:0x544e98484ed978fc, 0x8780...",https://www.google.com/maps/place//data=!4m2!3...
1274,111058951077443588250,Mellissa Newling,1491249563055,3,Orders wrong every time I go here. Takes forev...,None,None,0x878011faadb8eead:0xe778cbfd3bfbed0,KFC,"KFC, 603 E Sioux Ave, Pierre, SD 57501",...,-100.347168,Chicken wings restaurant,2.4,18,$,"[[Monday, 11AM–9PM], [Tuesday, 11AM–9PM], [Wed...","{'Service options': ['Delivery', 'Takeout'], '...",Permanently closed,"[0x878011faac2b47fb:0x544e98484ed978fc, 0x8780...",https://www.google.com/maps/place//data=!4m2!3...
1275,117708793057964375634,Darcy Green,1499523764411,2,I had taco bell food and it was cold. I waited...,None,None,0x878011faadb8eead:0xe778cbfd3bfbed0,KFC,"KFC, 603 E Sioux Ave, Pierre, SD 57501",...,-100.347168,Fast food restaurant,2.4,18,$,"[[Monday, 11AM–9PM], [Tuesday, 11AM–9PM], [Wed...","{'Service options': ['Delivery', 'Takeout'], '...",Permanently closed,"[0x878011faac2b47fb:0x544e98484ed978fc, 0x8780...",https://www.google.com/maps/place//data=!4m2!3...

In [32]:
restaurantes["category"].value_counts()

category
Restaurant                      1087
Pizza restaurant                 543
Delivery Restaurant              397
Takeout Restaurant               322
Chinese restaurant               297
Fast food restaurant             247
Asian restaurant                 221
Breakfast restaurant             164
Vegetarian restaurant            164
American restaurant              150
Italian restaurant               107
Tapas restaurant                  80
Taco restaurant                   63
Mexican restaurant                63
Restaurant supply store           56
Spanish restaurant                48
Latin American restaurant         48
Burrito restaurant                48
Seafood restaurant                47
Dominican restaurant              44
Ecuadorian restaurant             43
Colombian restaurant              41
Hawaiian restaurant               38
Health food restaurant            36
Gluten-free restaurant            30
Soup restaurant                   28
Chicken wings restaurant          25
Hot pot restaurant                24
Cajun restaurant                  21
Chicken restaurant                21
Asian fusion restaurant           20
Lunch restaurant                  17
Down home cooking restaurant      17
Cape Verdean restaurant           15
Portuguese restaurant             14
Tex-Mex restaurant                14
Delivery Chinese restaurant       13
Guatemalan restaurant             11
Japanese restaurant               11
Caribbean restaurant              11
Southern restaurant (US)          11
Norwegian restaurant              10
Name: count, dtype: int64

In [33]:
restaurantes["category"].unique()

array(['Fast food restaurant', 'American restaurant',
       'Chicken restaurant', 'Chicken wings restaurant', 'Restaurant',
       'Breakfast restaurant', 'Pizza restaurant', 'Norwegian restaurant',
       'Down home cooking restaurant', 'Takeout Restaurant',
       'Soup restaurant', 'Health food restaurant',
       'Dominican restaurant', 'Italian restaurant', 'Taco restaurant',
       'Cape Verdean restaurant', 'Seafood restaurant',
       'Restaurant supply store', 'Chinese restaurant',
       'Delivery Chinese restaurant', 'Mexican restaurant',
       'Delivery Restaurant', 'Asian restaurant', 'Hot pot restaurant',
       'Burrito restaurant', 'Latin American restaurant',
       'Spanish restaurant', 'Tapas restaurant', 'Vegetarian restaurant',
       'Japanese restaurant', 'Tex-Mex restaurant',
       'Guatemalan restaurant', 'Cajun restaurant',
       'Caribbean restaurant', 'Southern restaurant (US)',
       'Lunch restaurant', 'Colombian restaurant',
       'Asian fusion restaurant', 'Portuguese restaurant',
       'Hawaiian restaurant', 'Ecuadorian restaurant',
       'Gluten-free restaurant'], dtype=object)

In [42]:
palabra_clave = "lodging"
reviews_hotel = reviews_completo.dropna(subset="category")
filtro1 = reviews_hotel["category"].str.contains(palabra_clave, case=False)
hoteles = reviews_hotel[filtro1]
hoteles.head()

Empty DataFrame
Columns: [user_id, name_x, time, rating, text, pics, resp, gmap_id, name_y, address, description, latitude, longitude, category, avg_rating, num_of_reviews, price, hours, MISC, state, relative_results, url]
Index: []

[0 rows x 22 columns]